### ISSUE TITLE
Objective-C port AA-streaming

### ISSUE THREAD

**Issue by JSFun** [simon-weber/Unofficial-Google-Music-API#206]
So I ported some of the code on this repo to Objective-C and I would like to ask if someone knows how to receive All-Access songs streaming URLs? I wrote the code

    - (NSArray*)arrayWithSltAndSig{
      NSMutableString *salt = [NSMutableString new];
    
       NSArray *all = @[@"a", @"b", @"c", @"d", @"e", @"f", @"g", @"h", @"i", @"j", @"k", @"l", @"m", @"n", @"o", @"p", @"q", @"r", @"s", @"t", @"u", @"v", @"w", @"x", @"y", @"z", @"0", @"1", @"2", @"3", @"4", @"5", @"6", @"7", @"8", @"9"];
       for (int i = 0; i < 12; i++) {
           [salt appendString:[all objectAtIndex:arc4random()%[all count]]];
       }
    
       NSString *key = @"27f7313e-f75d-445a-ac99-56386a5fe879";
       NSString *data = [NSString stringWithFormat:@"%@%@", GPMid, salt];
    
       const char *cKey  = [key cStringUsingEncoding:NSASCIIStringEncoding];
       const char *cData = [data cStringUsingEncoding:NSASCIIStringEncoding];
    
       unsigned char cHMAC[CC_SHA256_DIGEST_LENGTH];
    
       CCHmac(kCCHmacAlgSHA256, cKey, strlen(cKey), cData, strlen(cData), cHMAC);
    
       NSData *HMAC = [[NSData alloc] initWithBytes:cHMAC length:sizeof(cHMAC)];
    
       NSString *hash = [[[[HMAC base64Encoding] stringByReplacingOccurrencesOfString:@"+" withString:@"-"] stringByReplacingOccurrencesOfString:@"/" withString:@"_"] stringByReplacingOccurrencesOfString:@"=" withString:@"."];
    
       NSLog(@"hash:%@", hash);
    
       return @[salt, hash];
    }

    - (void)getTrackURLWithHandler:(void(^)(NSString *trackURL))handler{
       NSArray *curArr = [self arrayWithSltAndSig];
        [GPMAPI requestWithPathExtention:[NSString stringWithFormat:@"play?u=0&songid=%@&pt=e&slt=%@&sig=%@", GPMid, curArr[0], curArr[1]] andMethod:@"GET" usingServicesExt:NO usingXTToken:NO withHandler:^(NSData *data) {
            NSError *err;
            NSLog(@"th:%@", [[NSString alloc] initWithData:data encoding:NSUTF8StringEncoding]);
        
        
            NSDictionary *urlDict = [NSJSONSerialization JSONObjectWithData:data options:0 error:&err];
            NSLog(@"dict:%@", urlDict);
            if (!err) {
                handler(urlDict[@"url"]);
            }
        }];
    }

Where
```+ (void)requestWithPathExtention:(NSString*)pathExtention andMethod:(NSString*)method usingServicesExt:(BOOL)usesServicesExt usingXTToken:(BOOL)usesXTToken withHandler:(void(^)(NSData *data))handler``` in 'GPMAPI'  is sending a request to the Google Play Music Service.

The problem is, that I'm still getting ```STREAM_ERROR_98``` along with the HTTP error ```Forbidden Error 403```. Any ideas on this?

**Comment by simon-weber** [comment]
I'm going to close this since it hasn't been updated in a while.

Feel free to reopen it if you're still running into problems.
