### ISSUE TITLE
getting playlists with webclient

### ISSUE THREAD

**Issue by bubbleguuum** [simon-weber/Unofficial-Google-Music-API#230]
This is not really an issue, but some information I've found and tested for retrieving playlists with web API, in case someone is interested. I know the webclient is kind of becoming deprecated but it still has its use. Moreover, the web API returns jsarray, which although annoying to parse, is a tad faster to parse than regular json. That's probably why Google use that on the web: to make loading as fast as possible.

Assuming you have a playlist id (an uuid), this call return the content of the songs contained in the playlist in correct order, in jsarray format:

POST request:  https://play.google.com/music/services/loaduserplaylist?u=0&xt=...&format=jsarray
POST body: [["",1],["&lt;playlist id&gt;"]]

Response:
```json
[[0,1]
,[[["5084d42c-884d-3440-aa8b-f78edba2199b","Steppingfilter 101","//lh3.googleusercontent.com/-Kwc9kOmSIy4yDZBHYWS9MzJb2GfSDgom1gMWr1vaJ3re3_BXIbnsfVgt0_c","Aphex Twin","Analord 01","",,,,,"","Abstract",,286000,1,7,0,0,2005,0,,,0,0,1379338055004349,1379745960008708,,,,2,"",,,"Acirogtcm4nkyvhghrt3bguv3tu",189,1379338078777000,,,,[]
,,,,"66c4cab3-ba67-3e99-b186-0c5bff6469f6"]
, 
song 2 as jsarray, 
...,
song n as jsarray, 
```
What's interesting is that you get all the songs of a playlist with a single call (no indirection like in the mobile client) including any All-Access songs 

Now the problem, is that I did not found a web API to retrieve the list of playlists (that is: their name and id among other attributes), eg the equivalent of mobileclient.ListPlaylists.

It seems that this info is buried in the response to the very first request that the Google Music web app makes to play.google.com, buried in a massive amount of HTML.

If anyone can find a way to list playlists with a web API call, that would be awesome.

**Comment by simon-weber** [comment]
I'm going to close this issue since it's pretty old.

As an aside, it looks like setting format=json actually works these days. That could make a lot of webclient requests viable again if we can also figure out an easy way to get the request schemas in json.
