### ISSUE TITLE
Song MetaData not up to date in the doc

### ISSUE THREAD

**Issue by henry-nicolas** [simon-weber/Unofficial-Google-Music-API#231]
Dear,

I'm using GMusicAPI 3.1.0 from PIP here and I have an issue regarding the SongMetadata array.
The key albumArtistNorm is well documented both in [0] and in [1].
However, when I print the array for one track I got after doing a load_all_songs(), I have:

albumArtRef, artistId, composer, trackType, id, album, totalDiscCount, title, creationTimestamp, recentTimestamp, albumArtist, trackNumber, discNumber, deleted, storeId, nid, totalTrackCount, estimatedSize, albumId, genre, artistArtRef, kind, artist, lastModifiedTimestamp, clientId, durationMillis

So apparently the doc doesn't match the available fields.

I assume it's needed to update the doc.

[0] http://unofficial-google-music-api.readthedocs.org/en/latest/reference/metadata.html
[1] https://github.com/simon-weber/Unofficial-Google-Music-API/blob/develop/docs/source/reference/metadata.rst

**Comment by simon-weber** [comment]
I removed these obsolete docs in a347304a8a1ff3837ec37cf4c9109509380115ec.
