### ISSUE TITLE
'lastRatingChangeTimestamp' not defined by 'properties'

### ISSUE THREAD

**Issue by soulfx** [simon-weber/Unofficial-Google-Music-API#308]
Another schema change:

ValidationException: Failed to validate field 'entries' list schema: additional
property 'lastRatingChangeTimestamp' not defined by 'properties' or 'patternProp
erties' are not allowed in field 'track'

{\n    "kind": "sj#track",\n    "title": "BACKIN BLACK",\n    "artist": "AC/DC JAM",\n    "composer": "",\n    "album": "AC/DC Jam - LIVE",\n    "albumArtist": "AC/DC Jam",\n    "year": 2012,\n    "trackNumber": 3,\n    "genre": "Rock",\n    "durationMillis": "227000",\n    "albumArtRef": [\n     {\n      "url": "http://lh3.ggpht.com/nRBrklERemvOfDhFF1MdeTo82u8neUwtlAbt4mikSaOiw5jGqftYULHwOSE118gPheVNxML-"\n     }\n    ],\n    "playCount": 1,\n    "discNumber": 1,\n    "rating": "1",\n    "estimatedSize": "9097958",\n "trackType": "7",\n    "storeId": "Tml6ptgcpl4cmtqvcuovgszldzy",\n    "albumId": "B2usa2ozlvshnsegiwzekk7r4za",\n    "artistId": [\n     "Aj22of2rszycycdyk5imfbq5vfq"\n    ],\n    "nid": "Tml6ptgcpl4cmtqvcuovgszldzy",\n    "trackAvailableForSubscription": true,\n    "trackAvailableForPurchase": true,\n    "albumAvailableForPurchase": true,\n    "contentType": "2",\n    "lastRatingChangeTimestamp": "1401491138184000"\n   }

**Comment by simon-weber** [comment]
closed by #309
