### ISSUE TITLE
Error "the response format for Search was not recognized" - Required field 'albumArtRef' is missing

### ISSUE THREAD

**Issue by aled** [simon-weber/Unofficial-Google-Music-API#311]
Got this error running against develop branch:

2015-02-03 23:21:11,341 - gmusicapi.Mobileclient1 (shared:281) [ERROR]: the response format for Search was not recognized.

Required field 'albumArtRef' is missing

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://www.googleapis.com/sj/v1.5/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': u'Joni Mitchell', 'max-results': 100}, 'method': 'GET'}

'{\n "kind": "sj#searchresponse",\n "entries": [\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Joni Mitchell",\n    "artistArtRef": "http://lh6.ggpht.com/3GLBksMlxJ3KClr8NeQyijK6WjpvAxmModiu2Km5nveqIqDMxPvPO8QtQMoqGdDQ_SGCS71Wmg",\n    "artistId": "Awatgo67d7s4din34scsnshrb4q"\n   },\n   "score": 839.6468505859375,\n   "best_result": true,\n   "navigational_result": true,\n   "navigational_confidence": 79.56826695456196\n  },\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Joni Mitchell Tribute Band",\n    "artistArtRef": "http://lh4.ggpht.com/KZqqkeSrGXmzGMxvpgLoylIs_yUG_zw-2aslX5KxiIJR0prpxLdG2hu8xK4h5KesHxU7UDGU",\n    "artistId": "Az32eagivmwbacsfsofxwfoisam"\n   },\n   "score": 21.10506820678711\n  },\n  {\n   "type": "2",\n   "artist": {\n    "kind": "sj#artist",\n    "name": "Joni Mitchell Tribute by Strings Attached",\n    "artistArtRef": "http://lh4.ggpht.com/IBKyeYvYi-jvQnrfYJ2oE0hirYzWygXcAgTqafAk1Kh2BWX3I2g1w4IF0aMsoZCSQv4zUBSOEQ",\n    "artistI...'

**Comment by simon-weber** [comment]
Great; thanks!
