### ISSUE TITLE
InsecureRequestWarning: Unverified HTTPS request is being made.

### ISSUE THREAD

**Issue by aug-riedinger** [simon-weber/Unofficial-Google-Music-API#313]
I get this message when uploading with the music manager:

```
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:734: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning
```

I tried to use: `Musicmanager(debug_logging=True, verify_ssl=False)` but it did not fix it.

I know it is simply a warning, but making a commandline utility out of it, it is pretty annoying ... 

Thanks

**Comment by simon-weber** [comment]
This is expected; I opt out of ssl verification in a few places where Google uses self-signed certs.

You can use this to suppress the error:
```python
from requests.packages.urllib3.exceptions import InsecureRequestWarning
requests.packages.urllib3.disable_warnings(InsecureRequestWarning)
```

I should probably just opt out inside gmusicapi. I'll leave this open until then.

For reference, here's the issue on requests: https://github.com/kennethreitz/requests/issues/2214. Once

**Comment by aug-riedinger** [comment]
Thanks for this complete answer!

Maybe this snippet should be imported only if `verify_ssl=false`, shouldn't it? 

Anyways, it always feels slightly hacky to remove warning the old way, doesn't it?

**Comment by aug-riedinger** [comment]
Thanks for this beautiful repo besides. It works like a charm, and I am only starting to explore all its possibilities!

**Comment by simon-weber** [comment]
> Maybe this snippet should be imported only if verify_ssl=false?

I think I need it even if gmusicapi-level verification is one, since there are spots where I opt out of verification regardless of that setting (eg https://github.com/simon-weber/Unofficial-Google-Music-API/blob/a01f04214cfd901dc4bf15e10fb7db0aefbad15a/gmusicapi/protocol/musicmanager.py#L105).

> Thanks for this beautiful repo

Thanks! :grin:

**Comment by simon-weber** [comment]
See https://github.com/simon-weber/Unofficial-Google-Music-API/issues/345#issuecomment-113845932 for an explanation.
