### ISSUE TITLE
401 unauthorized with webclient streaming

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Unofficial-Google-Music-API#318]
It looks like this:

```
CallFailure: GetStreamUrl: 401 Client Error: Unauthorized
(response was: '<HTML>\n<HEAD>\n<TITLE>Unauthorized</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Unauthorized</H1>\n<H2>Error 401</H2>\n</BODY>\n</HTML>\n')
```

I'd seen this in irc recently, but this is the first time I've noticed it in tests (eg https://travis-ci.org/simon-weber/Unofficial-Google-Music-API/jobs/53516041).

**Comment by thebigmunch** [comment]
Not sure if related because I really never looked at the calls coming from the Google Music webapp before, but there are a couple params I don't see in the gmusicapi protocol:

* mse (bool) - true for all the songs I've tried
* obfid (20 numbers) - per-account obfuscation id

**Comment by simon-weber** [comment]
I think mse refers to http://en.wikipedia.org/wiki/Media_Source_Extensions. I tried omitting it and setting it to false; both of them still got urls back.

It looks like the 401 is because clientlogin is no longer a supported auth method for the webclient. I think we can move to serviceloginauth instead (similar to the flow described [here](https://github.com/AndlyticsProject/andlytics/wiki/Developer-Console-v2---Login-Process)).

**Comment by codemaker1999** [comment]
In case this is helpful to anyone: I worked around this issue by looping through deviceIDs until one allowed streaming

```python
n = 0 # index of device id
while True:
    if n>50:
        print "Could not find working device ID :("
        quit()
    try:
        did = mc.get_registered_devices()[n]["id"];
        did = did if not did.startswith("0x") else did[2:] # need to omit the "0x" part
        url = mc.get_stream_url("Tuixudggy2n4c5dea25c6shmhse", did) # random track
        break
    except:
        n+=1
# now "did" is a device id that allows streaming
```

**Comment by simon-weber** [comment]
@codemaker1999 that's applicable to the mobileclient, not the webclient.
