### ISSUE TITLE
Song search/get song_id?

### ISSUE THREAD

**Issue by Neophyteone** [simon-weber/Unofficial-Google-Music-API#327]
Hi,

I've been playing with the api for a while and i really like it. I have not yet found a way to search for a title in google play music, to get a song_id so i can build playlists using CSV files etc. Will there be "search" support in gmusicapi Webclient?

Best regards

**Comment by simon-weber** [comment]
Two answers, depending on what you're trying to do:
* searching All Access songs: use [Mobileclient.search_all_access](https://unofficial-google-music-api.readthedocs.org/en/develop/reference/mobileclient.html#gmusicapi.clients.Mobileclient.search_all_access)
* searching uploaded songs in your library: there's no serverside support, and not likely to be any in the future. If you like, you could build a local search index like Google's clients do using something like [Whoosh](https://pythonhosted.org/Whoosh)

**Comment by soulfx** [comment]
Hi neo,

You may also wish to check out how I put together the search code in my playlist creator script. https://github.com/soulfx/gmusic-playlist   in the import list script look for the search_for_track method.  It's a bit brute force, but seems to work.

Regards

**Comment by Neophyteone** [comment]
Many thanks, so search_all_access is only doable using Mobileclient?

Thanks.

**Comment by simon-weber** [comment]
> Many thanks, so search_all_access is only doable using Mobileclient?

Correct.
