### ISSUE TITLE
api.search_all_access  in MobileClient not working

### ISSUE THREAD

**Issue by mgillespie** [simon-weber/Unofficial-Google-Music-API#328]
Using @soulfx playlist export script, I am seeing the following problems in both 4.x and 5.x branches.

Stack trace: (v4)

Logging into google music...
Login Successful.
DEBUG:gmusicapi.Mobileclient1:Search(args=['one u2', 1], kwargs={})
Traceback (most recent call last):
File "/root/gmusic-playlist/ExportLists.py", line 43, in 
api = open_api()
File "/root/gmusic-playlist/common.py", line 117, in open_api
dlog(u'Available track details: '+str(get_google_track_details()))
File "/root/gmusic-playlist/common.py", line 65, in get_google_track_details
return (api.search_all_access(sample_song,max_results=1)
File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/mobileclient.py", line 796, in search_all_access
res = self._make_call(mobileclient.Search, query, max_results)
File "/usr/local/lib/python2.7/dist-packages/gmusicapi/clients/shared.py", line 80, in _make_call
return protocol.perform(self.session, self.validate, args, *kwargs)
File "/usr/local/lib/python2.7/dist-packages/gmusicapi/protocol/shared.py", line 225, in perform
raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: Search: 404 Client Error: Not Found
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/query', 'headers': {'Authorization': ''}, 'params': {'q': 'one u2', 'max-results': 1}, 'method': 'GET'})
(response was: '{\n "error": {\n "errors": [\n {\n "domain": "global",\n "reason": "notFound",\n "message": "Not Found"\n }\n ],\n "code": 404,\n "message": "Not Found"\n }\n}\n'

**Comment by simon-weber** [comment]
Can you try this again from the develop branch? It's working for me.

**Comment by mgillespie** [comment]
Not working here with latest dev commit (32e06f127c3a32140bca7ff9bddb6838d99f0dc9)

Could it be regional?  (UK)
Could it be that I am an ex-All Access subscriber?  (it's called "search_all_access", but I let my subscription expire a while back).  There is no mention that an all access subscription is needed to call this API, not in @soulfx  docs.

Trace:

Logging into google music...
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py:768: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Login Successful.
Traceback (most recent call last):
  File "/root/gmusic-playlist/ExportLists.py", line 43, in <module>
    api = open_api()
  File "/root/gmusic-playlist/common.py", line 117, in open_api
    dlog(u'Available track details: '+str(get_google_track_details()))
  File "/root/gmusic-playlist/common.py", line 65, in get_google_track_details
    return (api.search_all_access(sample_song,max_results=1)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-5.0.0.dev0-py2.7.egg/gmusicapi/clients/mobileclient.py", line 907, in search_all_access
    res = self._make_call(mobileclient.Search, query, max_results)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-5.0.0.dev0-py2.7.egg/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-5.0.0.dev0-py2.7.egg/gmusicapi/protocol/shared.py", line 226, in perform
    raise CallFailure(err_msg, call_name)
gmusicapi.exceptions.CallFailure: Search: 404 Client Error: Not Found
(requests kwargs: {'url': 'https://mclients.googleapis.com/sj/v1.11/query', 'headers': {'Authorization': '<omitted>'}, 'params': {'q': 'one u2', 'max-results': 1}, 'method': 'GET'})
(response was: '{\n "error": {\n  "errors": [\n   {\n    "domain": "global",\n    "reason": "notFound",\n    "message": "Not Found"\n   }\n  ],\n  "code": 404,\n  "message": "Not Found"\n }\n}\n')

**Comment by mgillespie** [comment]
OK, subscribed to all access and it's working...  Sorry for the confusion.   Perhaps it could be made clearer in the docs, that an all access subscription is required for this to work.

**Comment by simon-weber** [comment]
Ah, ok. Suggestions on how to reword the docs? I think it's pretty prominent right now: https://github.com/simon-weber/Unofficial-Google-Music-API/blob/32e06f127c3a32140bca7ff9bddb6838d99f0dc9/gmusicapi/clients/mobileclient.py#L767.
