### ISSUE TITLE
Avoiding "Less Secure Apps" Classification by Google

### ISSUE THREAD

**Issue by michael-lumley** [simon-weber/Unofficial-Google-Music-API#329]
Love the library. I've gotten it working successfully by extending the <a href="https://github.com/jamon/playmusic">node port</a> of this library, but the node port uses ClientLogin which has been depreciated by Google, an issue which has been <a href="https://github.com/simon-weber/Unofficial-Google-Music-API/issues/323">well</a> <a href="https://github.com/simon-weber/Unofficial-Google-Music-API/issues/318">discussed</a> here. ClientLogin is still working for me (at least it was a week or so ago the last time I tried it) but in order to gain access to my account through ClientLogin I had to enable access to 'less seccure apps' in my google security center.

Somewhat discouraged by that, I tried using <a href="https://github.com/simon-weber/Unofficial-Google-Music-API/issues/290">the v1beta1 version of the Skyjam scope</a>, and that worked well for me, but I ran into a problem with the playlist and playlistentry mutation endpoints. They return nothing and have no effect, though so far as I can tell they definitely exist. Perhaps I am not calling them with the right parameters, but if so, Google isn't giving me any help on that front with error messages.

Ultimately, I don't care which way of accessing the API I use, but I would like to have access without having to enable 'less secure apps.' Is there any workaround to this problem currently, or is 'less secure' the only option?

**Comment by simon-weber** [comment]
I believe the only current way to avoid "less secure access" is to use the [musicmanager](http://unofficial-google-music-api.readthedocs.org/en/develop/reference/musicmanager.html) interface. That's fairly limited, though, and everything else still uses clientlogin.

**Comment by michael-lumley** [comment]
I looked through the musicmanager documentation, but did not see any documented way of creating or editing playlists. Musicmanager must have some endpoints with that functionality, however, because google will import playlists from iTunes through the desktop client. Do we know anything about any of those endpoints that's not in the documentation?

**Comment by simon-weber** [comment]
I looked into those calls ages ago but never actually implemented them.

If this is something you're interested in taking on, ping me on irc and I can help get you set up.

**Comment by michael-lumley** [comment]
I'd love to do a pull, but I don't write Python, only Node/Javascript. Can you point me in the right direction in terms of investigating the calls?

**Comment by simon-weber** [comment]
Sure thing. Either shoot me an email or [ping me on irc](http://webchat.freenode.net/?channels=gmusicapi).

**Comment by michael-lumley** [comment]
@simon-weber Is there some secret to encoding the calls to music manager? I've intercepted the calls and found the proper structure, but when I try to send them off to the server, all I get in reply is a "malformed or illegal request" 400 error. I can get a token and log in, but past that, I can't even seem to get the client authentication method working.

I'm using protobuf.js to encode the calls, using your .proto files from the reversing repository and setting the request encoding to binary. I've also set the following headers:

    'User-Agent': 'Music Manager (1, 0, 55, 7425 HTTPS - Windows)'
    'Accept': '*/*'
    'Content-Type': 'application/x-google-protobuf'
    'Content-Length' : {dynamic}

Any suggestions?

**Comment by simon-weber** [comment]
Maybe you can crib some code from https://code.google.com/p/google-musicmanager-js/? They had everything working at one point.

**Comment by michael-lumley** [comment]
That looks like exactly what I was looking for. Thanks!

**Comment by simon-weber** [comment]
Oh, and this fixes the "less secure apps" problem for the mobileclient: https://github.com/simon-weber/Unofficial-Google-Music-API/issues/168#issuecomment-102190479.
