### ISSUE TITLE
Error with mobile_api.create_station

### ISSUE THREAD

**Issue by chrisnorman7** [simon-weber/Unofficial-Google-Music-API#331]
Hi,
First of all, absolutely loving gmusicapi! I've made me a fully-featured Google Music player with WX, and it rocks!

When I try and create a genre radio station, I get this error... Not sure if it's me or not:

The way I'm getting this is pretty much:
mobile_api.create_station(genre_id = mobile_api.get_genres()['genres'][3]['id'])

That's from memory, so hopefully the code is right! :package: 
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core.py", line 16766, in <lambda>
    lambda event: event.callable(*event.args, **event.kw) )
  File "/Users/chris/Dropbox/SRC/gmp/functions.py", line 489, in station_from_genre
    id = application.mobile_api.create_station(dlg.GetValue(), genre_id = genre['id'])
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/mobileclient.py", line 596, in create_station
    res = self._make_call(mutate_call, [add_mutation])
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/clients/shared.py", line 80, in _make_call
    return protocol.perform(self.session, self.validate, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/protocol/shared.py", line 246, in perform
    cls.check_success(response, parsed_response)
  File "/usr/local/lib/python2.7/site-packages/gmusicapi/protocol/mobileclient.py", line 350, in check_success
    cls.__name__)
gmusicapi.exceptions.CallFailure: BatchMutateStations: The server reported failure while changing the requested resource. If this wasn't caused by invalid arguments or server flakiness, please open an issue.
(requests kwargs: {'url': 'https://www.googleapis.com/sj/v1.5/radio/editstation', 'headers': {'Content-Type': 'application/json', 'Authorization': '<omitted>'}, 'data': '{"mutations": [{"create": {"tracks": [], "seed": {"genreId": "CHILDREN_MUSIC"}, "imageType": 1, "deleted": false, "lastModifiedTimestamp": "-1", "recentTimestamp": "1431736215670854", "clientId": "b8f9e500-fb62-11e4-8c5c-2cbe08f0fd6a", "name": "Genre station for Children\'s Music"}, "includeFeed": false, "params": {"contentFilter": 1}, "numEntries": 0}]}', 'method': 'POST', 'params': {'alt': 'json'}})
(response was: '{\n "mutate_response": [\n  {\n   "id": "",\n   "response_code": "INVALID_REQUEST"\n  }\n ]\n}\n')

**Comment by simon-weber** [comment]
I think I just fixed this yesterday =) Give the develop branch a shot and let me know if that works.

**Comment by chrisnorman7** [comment]
Hiya mate,
Yeah, works perfectly now. Thanks a lot.

Just as an aside, is the Android ID you need to pass to Mobileclient.login important? I just set it to 1234567890abcdef, as per the doc string… Should I be getting a valid key from Google or anything?

Cheers, and thanks again for a great API! Since Spotify broke all accessibility with their desktop client, and never introduced it with the web client, I’ve missed playing music on a computer… Thanks to you, I can now do that again!!!

Take care,
Chris Norman
chris.norman2@googlemail.com

**Comment by simon-weber** [comment]
I don't think there's much in the way of backend restrictions for the android id, but I'd recommend using one that's already registered to you if possible. Weird stuff may happen if you share one belonging to another user.

**Comment by chrisnorman7** [comment]
Ah I see, tar.

I don’t have an Android device, so I’ll just stick with my pretend one until something bad happens! :-)

Cheers,


Take care,
Chris Norman
chris.norman2@googlemail.com
