### ISSUE TITLE
Requests Error when app is bundled

### ISSUE THREAD

**Issue by chrisnorman7** [simon-weber/Unofficial-Google-Music-API#334]
Sorry, you'll be bored of hearing from me soon!

When using py2app with my app which uses gmusicapi, I can't run it, because I get this error:

Traceback (most recent call last):
  File "/Applications/Google Music Player.app/Contents/Resources/__boot__.py", line 351, in <module>
    _run()
  File "/Applications/Google Music Player.app/Contents/Resources/__boot__.py", line 336, in _run
    exec(compile(source, path, 'exec'), globals(), globals())
  File "/Applications/Google Music Player.app/Contents/Resources/main.py", line 8, in <module>
    if not uid or not pwd or not application.mobile_api.login(uid, pwd, application.app_id) or not application.web_api.login(uid, pwd):
  File "gmusicapi/clients/webclient.pyc", line 60, in login
  File "gmusicapi/session.pyc", line 108, in login
  File "gmusicapi/protocol/shared.pyc", line 209, in perform
  File "gmusicapi/session.pyc", line 76, in send
  File "gmusicapi/session.pyc", line 43, in _send_without_auth
  File "requests/sessions.pyc", line 465, in request
  File "requests/sessions.pyc", line 573, in send
  File "requests/adapters.pyc", line 431, in send
requests.exceptions.SSLError: [Errno 20] Not a directory

Do I need to bundle something extra with my app? Or is this a bug? I included a snippet of code I found on this site in main.py file:
 from requests.packages.urllib3.exceptions import InsecureRequestWarning
 requests.packages.urllib3.disable_warnings(InsecureRequestWarning)

That's the only bit of the code I can think may be relevant.

Cheers for any advice.

**Comment by simon-weber** [comment]
I always welcome bug reports =)

This is an odd one. Can you pull up the last line of code (in requests) that the error refers to? I'm thinking requests may have changed its interface in a newer version.

The snippet you posted shouldn't be related -- there's an open issue about that one.

**Comment by chrisnorman7** [comment]
No problem… I didn’t know which bit you wanted, so I included a block. The line with the * at the start is line 431.

                    r = low_conn.getresponse()
                    resp = HTTPResponse.from_httplib(
                        r,
                        pool=conn,
                        connection=low_conn,
                        preload_content=False,
                        decode_content=False
                    )
                except:
                    # If we hit any problems here, clean up the connection.
                    # Then, reraise so that we can handle the actual exception.
                    low_conn.close()
                    raise
                else:
                    # All is well, return the connection to the pool.
                    conn._put_conn(low_conn)

        except (ProtocolError, socket.error) as err:
            raise ConnectionError(err, request=request)

        except MaxRetryError as e:
            if isinstance(e.reason, ConnectTimeoutError):
                raise ConnectTimeout(e, request=request)

            if isinstance(e.reason, ResponseError):
                raise RetryError(e, request=request)

            raise ConnectionError(e, request=request)

        except _ProxyError as e:
            raise ProxyError(e)

        except (_SSLError, _HTTPError) as e:
            if isinstance(e, _SSLError):
*               raise SSLError(e, request=request)
            elif isinstance(e, ReadTimeoutError):
                raise ReadTimeout(e, request=request)
            else:
                raise

        return self.build_response(request, resp)


Take care,
Chris Norman
chris.norman2@googlemail.com

**Comment by chrisnorman7** [comment]
I just tried setting verify_ssl = False when I create the Mobileclient and the Webclient objects. That seems to have stopped the problem.

**Comment by simon-weber** [comment]
Good to know.

**Comment by simon-weber** [comment]
This issue hasn't been updated in a while, so I'm closing it. Feel free to reopen if you're still having trouble.

**Comment by peircej** [comment]
Hi Simon,

Sorry, this still seems to be an issue. We have an app that we bundle using py2app and get what looks like the same issue. Just trying to run:

    import requests
    r= requests.get('https://api.github.com/events')

we get:

```
Traceback (most recent call last):
  File "/Users/lpzjwp/Dropbox/psychopyStuff/sandbox/testOSF.py", line 2, in <module>
    r= requests.get('https://api.github.com/events')
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/requests/api.py", line 69, in get
    return request('get', url, params=params, **kwargs)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/requests/api.py", line 50, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/requests/sessions.py", line 465, in request
    resp = self.send(prep, **send_kwargs)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 20] Not a directory
```

The OP got success by turning off checking for SSL? How do I go about that?
Jon

**Comment by simon-weber** [comment]
@peircej are you using gmusicapi? Not to suggest that this isn't a problem - it certainly seems like one - but if you're not, it's probably better to let the requests folks know.

**Comment by peircej** [comment]
haha, sorry. Because the error listed above was about `requests` I thought this was the `requests` list. My apologies! ;-)

**Comment by simon-weber** [comment]
No problem :grin:
