### ISSUE TITLE
Webclient.login() 4th argument?

### ISSUE THREAD

**Issue by Neophyteone** [simon-weber/Unofficial-Google-Music-API#340]
Hi, i updated to develop branch today to solve authentication problem. However i now notice when i call ```
webclient.login("email", "password")
``` i get
```
TypeError: login() takes exactly 4 arguments (3 given)
```

If i add a bogus argument to:
 ```
webclient.login("email", "password", "randomcharacters")
```

I successfully authenticate. Before updating to develop and before the auth broke i could call webclient.login with just email and password.

**Comment by simon-weber** [comment]
It's an android id, as mentioned in the docs: https://unofficial-google-music-api.readthedocs.org/en/develop/reference/mobileclient.html#gmusicapi.clients.Mobileclient.login. I wouldn't recommend using a random one.

**Comment by Neophyteone** [comment]
Sorry - my bad, many thanks

**Comment by simon-weber** [comment]
Sure, no worries.
