### ISSUE TITLE
oauth.cred save issue

### ISSUE THREAD

**Issue by pinkienort** [simon-weber/Unofficial-Google-Music-API#344]
I tried to oauth with  setting `oauth_filepath`, then a error occurred.
Normal user does not execute because of permission error about directory access.
So I tried with super user.
Then, a oauth.cred file is located to setting `oauth_filepath`, but `gmusicapi.clients.OAUTH_FILEPATH` is different from setting `oauth_filepath`.

It's the following code I tried to execute. 
```python
from gmusicapi import Mobileclient
api = Mobileclient()
logged_in = api.login('mail@address.com', 'password')

from gmusicapi import Musicmanager
mm = Musicmanager()
mm.perform_oauth('/want/to/save/paht/oauth.cred', 0)

import gmusicapi.clients
print gmusicapi.clients.OAUTH_FILEPATH
```

**Comment by simon-weber** [comment]
This behavior is intended, though perhaps the docs are misleading: `gmusicapi.clients.OAUTH_FILEPATH` will only ever point to the default path.

If you pass a different path to perform_oauth, you need to also provide it when calling login, eg:
```python
# only needs to be done once:
from gmusicapi import Musicmanager
mm = Musicmanager()
mm.perform_oauth('/some/path/file.cred')
```

```python
# later, perhaps in a different script
from gmusicapi import Musicmanager
mm = Musicmanager()
mm.login('/some/path/file.cred')
```

**Comment by thebigmunch** [comment]
> This behavior is intended, though perhaps the docs are misleading: gmusicapi.clients.OAUTH_FILEPATH will only ever point to the default path.

Well, technically, you can change it after it's been imported. But it wouldn't really make sense to do so over simply assigning the credential file path to your own variable for convenience.

**Comment by pinkienort** [comment]
@simon-weber, thank you for your advice. I tried to do with your writing code, then my song was uploaded to my Google Play Music. I could used the oauth.cred which was located by `Musicmanager.perform_oauth`'s option, storage_filepath.
So I logined with the oauth.cred which a option, `oauth_credentials` in 'Musicmanager.login` set.

Thank you, @simon-weber.

**Comment by simon-weber** [comment]
:+1: glad I could help
