### ISSUE TITLE
Use certify module to avoid urllib3 warnings

### ISSUE THREAD

**Issue by sucotronic** [simon-weber/Unofficial-Google-Music-API#345]
Every https call fires a urllib3 warning. According to urllib3 doc(https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning) the correct way to avoid it would be to use **certifi** module which contains root certificates(https://urllib3.readthedocs.org/en/latest/security.html#certifi-with-urllib3).

**Comment by thebigmunch** [comment]
There are a couple things regarding this.

1. The issue of getting the warnings is a problem with requests not catching/disabling them when they offer the ability to disable verification. There is an open issue on their repo that will be dealt with when they get to it. This is the proper solution.

2. To my knowledge, disabling verification is necessary due to Google using self-signed certs in certain places. Using Certifi would not help with this.

**Comment by simon-weber** [comment]
Alternatively, we could look into shipping Google's self-signed cert with gmusicapi so we can trust it. I've never tried that, but I can't imagine it's too difficult.

**Comment by sucotronic** [comment]
Adding the Google certificates would be great. Anyway, you can put at any moment a simple ```urllib3.disable_warnings()``` and user will continue to live happy :P

**Comment by simon-weber** [comment]
This was my bad -- the certs weren't bad, they just required extra libraries (or a more recent python) to be able to verify them. Validation should be on everywhere by default now.

**Comment by siebert** [comment]
The minimum python version must be changed to 2.7.9, otherwise the following issue will prevent the login:

http://stackoverflow.com/questions/30652989/python-requests-sslerror

**Comment by simon-weber** [comment]
I was under the impression that sni worked fine with 2.7.x with the extra dependencies. Is that wrong?

**Comment by siebert** [comment]
I had 2.7.6 and got the error mentioned in the stackoverflow question. I found it via google, updated to 2.7.10 and now I can login again.

**Comment by simon-weber** [comment]
Hm, I can't recreate that. What I did:
* switch to 2.7.6 with pyenv
* create a new virtualenv
* pip install -e the most recent version, which pulled down the dependencies listed here: https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning
* ran tests without seeing the error

I'm on osx, and here's the output of pip freeze:
```
(env-276)~/other/gmusicapi$ (*p*) pip freeze
appdirs==1.4.0
beautifulsoup4==4.3.2
cffi==1.1.2
cryptography==0.9.1
decorator==3.4.2
enum34==1.0.4
-e git+git@github.com:simon-weber/gmusicapi.git@53d543bf1a1e341e7d3c4f896959477f66a24646#egg=gmusicapi-develop
gpsoauth==0.0.4
httplib2==0.9.1
idna==2.0
ipaddress==1.0.7
MechanicalSoup==0.3.1
mock==1.0.1
mutagen==1.29
ndg-httpsclient==0.4.0
oauth2client==1.4.11
proboscis==1.2.6.0
protobuf==2.6.1
pyasn1==0.1.8
pyasn1-modules==0.0.5
pycparser==2.14
pycrypto==2.6.1
pyOpenSSL==0.15.1
python-dateutil==2.4.2
requests==2.7.0
rsa==3.1.4
six==1.9.0
validictory==1.0.0
wheel==0.24.0
```
