### ISSUE TITLE
Is Playlist support included for All-Access? 

### ISSUE THREAD

**Issue by rolandrohde** [simon-weber/Unofficial-Google-Music-API#346]
Hi, 

is it possible to access generated and/or user-created Playlists via this API? It's currently not implemented in Hechtus' Squeezebox Plugin, but I'd like to know whether it's at least possibly  via the API. 
I mean all-access Playlists like the auto-generated "Favourites" PL. Radio Stations work fine, apart from the fact that Hechtus' Plugin does not report those created on LMS back to the Google Servers, but searching and browsing Playlists would beba really cool addition. 
Thanks!

**Comment by simon-weber** [comment]
User-created playlists should be returned by https://unofficial-google-music-api.readthedocs.org/en/develop/reference/mobileclient.html#gmusicapi.clients.Mobileclient.get_all_playlists. Saved instant mixes should be included.

Auto-playlists like "thumbs up" and "last added" weren't stored serverside last time I checked. You can calculate an approximation relatively easily with code like this: https://gist.github.com/simon-weber/5007769.
