### ISSUE TITLE
Reporting as Requested

### ISSUE THREAD

**Issue by devsda** [simon-weber/Unofficial-Google-Music-API#348]
The following was created from the head of origin/develop ...

2015-06-15 01:44:53,755 - gmusicapi.Mobileclient1 (shared:282) [ERROR]: the response format for GetAlbum was not recognized.

Value {u'albumArtRef': [{u'url': u'http://lh5.ggpht.com/DQC4uOiftkDi1yAih8oZZ-HssE-NCGI7oJnAiHggZ0G1z_qQtBeKbajsCEkqeO09xpCV0yB5Gw'}], u'artistId': [u'A5djvbhay4af6o5djlzewr4t6qe'], u'composer': u'', u'year': 2015, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Popular, Sentimental & World War I Songs (Encore 1) [Recorded 1914 - 1928]', u'title': u"It's a Long Way to Tipperary (World War 1) [Recorded 1914]", u'albumArtist': u'John McCormack', u'trackNumber': 1, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'T5kqvckoc4c3iwziotq24cqwdbu', u'nid': u'T5kqvckoc4c3iwziotq24cqwdbu', u'estimatedSize': u'7779292', u'albumId': u'Bpxly77go2nqnw6glmfgcuphafy', u'genre': u'Vocal/Easy Listening', u'playCount': 1, u'kind': u'sj#track', u'artist': u'John McCormack', u'lastModifiedTimestamp': u'1434346174542069', u'durationMillis': u'194000'} for field '<obj>.tracks[0]' contains additional property 'lastModifiedTimestamp' not defined by 'properties' or 'patternProperties' and additionalProperties  is False

First, try the develop branch. If you can recreate this error with the most recent code please [create an issue](http://goo.gl/qbAW8) that includes the above ValidationException and the following request/response:
{'url': 'https://mclients.googleapis.com/sj/v1.11/fetchalbum', 'headers': {'Authorization': '<omitted>'}, 'params': {'alt': 'json', 'nid': u'Bpxly77go2nqnw6glmfgcuphafy', 'include-tracks': True}, 'method': 'GET'}

'{\n "kind": "sj#album",\n "name": "Popular, Sentimental & World War I Songs (Encore 1) [Recorded 1914 - 1928]",\n "albumArtist": "John McCormack",\n "albumArtRef": "http://lh5.ggpht.com/DQC4uOiftkDi1yAih8oZZ-HssE-NCGI7oJnAiHggZ0G1z_qQtBeKbajsCEkqeO09xpCV0yB5Gw",\n "albumId": "Bpxly77go2nqnw6glmfgcuphafy",\n "artist": "John McCormack",\n "artistId": [\n  "A5djvbhay4af6o5djlzewr4t6qe"\n ],\n "year": 2015,\n "tracks": [\n  {\n   "kind": "sj#track",\n   "lastModifiedTimestamp": "1434346174542069",\n   "title": "It\'s a Long Way to Tipperary (World War 1) [Recorded 1914]",\n   "artist": "John McCormack",\n   "composer": "",\n   "album": "Popular, Sentimental & World War I Songs (Encore 1) [Recorded 1914 - 1928]",\n   "albumArtist": "John McCormack",\n   "year": 2015,\n   "trackNumber": 1,\n   "genre": "Vocal/Easy Listening",\n   "durationMillis": "194000",\n   "albumArtRef": [\n    {\n     "url": "http://lh5.ggpht.com/DQC4uOiftkDi1yAih8oZZ-HssE-NCGI7oJnAiHggZ0G1z_qQtBeKbajsCEkqeO09xpCV0yB5Gw"\n    }\n   ],\n   "playCoun...'

A traceback follows:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-5.1.0.dev0-py2.7.egg/gmusicapi/protocol/shared.py", line 249, in perform
    cls.validate(response, parsed_response)
  File "/usr/local/lib/python2.7/dist-packages/gmusicapi-5.1.0.dev0-py2.7.egg/gmusicapi/protocol/mobileclient.py", line 262, in validate
    return validictory.validate(msg, cls._res_schema)
  File "/usr/local/lib/python2.7/dist-packages/validictory/__init__.py", line 36, in validate
    return v.validate(data, schema)
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 543, in validate
    self.__validate("data", {"data": data}, schema, '<obj>')
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 244, in validate_properties
    path + '.' + eachProp)
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 275, in validate_items
    '{}[{}]'.format(path, index))
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 566, in __validate
    validator(data, fieldname, schema, path, newschema.get(schemaprop))
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 353, in validate_additionalProperties
    " is False", value, fieldname, prop=eachProperty, path=path)
  File "/usr/local/lib/python2.7/dist-packages/validictory/validator.py", line 176, in _error
    raise err
ValidationException: Value {u'albumArtRef': [{u'url': u'http://lh5.ggpht.com/DQC4uOiftkDi1yAih8oZZ-HssE-NCGI7oJnAiHggZ0G1z_qQtBeKbajsCEkqeO09xpCV0yB5Gw'}], u'artistId': [u'A5djvbhay4af6o5djlzewr4t6qe'], u'composer': u'', u'year': 2015, u'trackAvailableForSubscription': True, u'trackType': u'7', u'album': u'Popular, Sentimental & World War I Songs (Encore 1) [Recorded 1914 - 1928]', u'title': u"It's a Long Way to Tipperary (World War 1) [Recorded 1914]", u'albumArtist': u'John McCormack', u'trackNumber': 1, u'discNumber': 1, u'albumAvailableForPurchase': True, u'contentType': u'2', u'trackAvailableForPurchase': True, u'storeId': u'T5kqvckoc4c3iwziotq24cqwdbu', u'nid': u'T5kqvckoc4c3iwziotq24cqwdbu', u'estimatedSize': u'7779292', u'albumId': u'Bpxly77go2nqnw6glmfgcuphafy', u'genre': u'Vocal/Easy Listening', u'playCount': 1, u'kind': u'sj#track', u'artist': u'John McCormack', u'lastModifiedTimestamp': u'1434346174542069', u'durationMillis': u'194000'} for field '<obj>.tracks[0]' contains additional property 'lastModifiedTimestamp' not defined by 'properties' or 'patternProperties' and additionalProperties  is False

**Comment by simon-weber** [comment]
Thanks! This looks like an easy fix.
