### ISSUE TITLE
Support 'fix incorrect match'

### ISSUE THREAD

**Issue by simon-weber** [simon-weber/Unofficial-Google-Music-API#89]
This feature requires a local record of all uploads, since the protocol works like:
* client (ie gmusicapi or Music Manager) wants to upload a song called `a`
* server matches `a` to serverside `b` and tells the client there's no need to upload
* ...later, user tells server that `b` is not a correct match
* server notifies client that `b` was an incorrect match
* client must match `b` to `a`, then reupload

There are non-trivial decisions behind this feature, so it shouldn't be rushed.

**Comment by jonboy345** [comment]
I've got a pile of songs that have been matched incorrectly within GPM.

What would be your advice on how to fix this? Was looking through the documentation and came across this. Would it be best to just delete my music from the GPM server and reupload using enable-matching false? Or someway to parse through my library and have every song that is a possible incorrect match marked as such so Music Manager will upload my version of the file?

Thanks in advance. This is an awesome project!

**Comment by simon-weber** [comment]
If they were uploaded with gmusicapi - and past Simon's understanding still applies - you'd have to reupload them. Neither gmusicapi nor Google's Music Manager have the necessary mapping to know what to reupload once they're marked as incorrect. It's worth testing what happens when you mark them first, though -- maybe the protocol is different these days and stores the original file regardless.

If they were uploaded with the Music Manager and you just need to quickly mark them all, the free version of https://autoplaylists.simon.codes should let you quickly find them and make a playlist. Then you can select-all > mark incorrect match.

**Comment by jonboy345** [comment]
That's awesome. Was able to use the autoplaylists extension and created a playlist with Type 6 "uploaded and matched" to quickly mark all uploaded songs as an incorrect match.

Thank you, Simon!
